// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

import { createHmac, randomBytes } from "node:crypto";

export const VERSION = "1.0.5";
export const DEFAULT_BASE_URL = "https://api.sigwise.ai";

/** How long each request token is valid for, in seconds (the API allows 300). */
const TOKEN_TTL_SECONDS = 60;

export interface ClientOptions {
  /** The API key ID. Defaults to the `SIGWISE_API_KEY` environment variable. */
  apiKey?: string;
  /**
   * The API key's signing secret. Defaults to `SIGWISE_SECRET`. It
   * signs a short-lived token for every request and is never sent itself.
   */
  secret?: string;
  /** Defaults to `SIGWISE_BASE_URL`, then `https://api.sigwise.ai`. */
  baseUrl?: string;
  /** Per-attempt timeout in milliseconds. Default 30000. */
  timeout?: number;
  /** How many times to retry idempotent requests after a network error, a 429 or a 5xx. Default 2. */
  maxRetries?: number;
  /** Headers sent with every request. */
  headers?: Record<string, string>;
  /** A `fetch` implementation. Defaults to the global one (Node 18+). */
  fetch?: typeof fetch;
}

export interface RequestOptions {
  /** Overrides the client's timeout for this request, in milliseconds. */
  timeout?: number;
  /** Overrides the client's retry count for this request. */
  maxRetries?: number;
  /** Aborts the request. */
  signal?: AbortSignal;
  /** Extra headers for this request. */
  headers?: Record<string, string>;
}

/** The API answered with an error status. */
export class SigWiseError extends Error {
  /** The HTTP status code. */
  readonly status: number;
  /** The machine-readable error code, e.g. `not_found`. */
  readonly code: string;
  /** The decoded response body. */
  readonly body: unknown;
  readonly headers: Headers;

  constructor(status: number, code: string, message: string, body: unknown, headers: Headers) {
    super(message);
    this.name = "SigWiseError";
    this.status = status;
    this.code = code;
    this.body = body;
    this.headers = headers;
  }
}

/** The request never got a response: a network error, a timeout or an abort. */
export class SigWiseConnectionError extends Error {
  constructor(message: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = "SigWiseConnectionError";
  }
}

function base64url(input: string | Buffer): string {
  return Buffer.from(input).toString("base64url");
}

/**
 * Signs the HS256 JWT that authenticates one request: `kid` names the key,
 * `iat`/`exp` bound its lifetime, and `htm`/`htu` bind it to the method and
 * path so it can't be replayed against another endpoint.
 */
export function signRequestToken(
  apiKey: string,
  secret: string,
  method: string,
  path: string,
  now: number = Math.floor(Date.now() / 1000),
): string {
  const header = base64url(JSON.stringify({ alg: "HS256", typ: "JWT", kid: apiKey }));
  const claims: Record<string, unknown> = {
    iat: now,
    exp: now + TOKEN_TTL_SECONDS,
    jti: randomBytes(16).toString("hex"),
    htm: method.toUpperCase(),
  };
  // The server compares htu with the decoded path, so only bind paths it can
  // read back unchanged.
  if (!/[?#]/.test(path)) claims.htu = path;
  const payload = base64url(JSON.stringify(claims));
  const signature = createHmac("sha256", secret).update(`${header}.${payload}`).digest("base64url");
  return `${header}.${payload}.${signature}`;
}

export interface RequestSpec {
  method: string;
  /** A path template such as `/v1/objects/{object_id}`. */
  path: string;
  pathParams?: Record<string, string>;
  query?: object;
  body?: unknown;
}

const RETRY_STATUSES = new Set([408, 429, 500, 502, 503, 504]);
const IDEMPOTENT = new Set(["GET", "HEAD", "PUT", "DELETE", "OPTIONS"]);

/** The transport shared by every resource. */
export class Core {
  readonly apiKey: string;
  readonly baseUrl: string;
  private readonly secret: string;
  private readonly timeout: number;
  private readonly maxRetries: number;
  private readonly headers: Record<string, string>;
  private readonly fetchImpl: typeof fetch;

  constructor(options: ClientOptions = {}) {
    const env = typeof process !== "undefined" ? process.env : {};
    const apiKey = options.apiKey ?? env.SIGWISE_API_KEY;
    const secret = options.secret ?? env.SIGWISE_SECRET;
    if (!apiKey || !secret) {
      throw new Error(
        "SigWise: an API key and its secret are required. Pass { apiKey, secret } or set SIGWISE_API_KEY and SIGWISE_SECRET.",
      );
    }
    this.apiKey = apiKey;
    this.secret = secret;
    this.baseUrl = (options.baseUrl ?? env.SIGWISE_BASE_URL ?? DEFAULT_BASE_URL).replace(/\/+$/, "");
    this.timeout = options.timeout ?? 30_000;
    this.maxRetries = options.maxRetries ?? 2;
    this.headers = options.headers ?? {};
    const f = options.fetch ?? globalThis.fetch;
    if (!f) throw new Error("SigWise: no fetch implementation found; pass one as options.fetch (Node 18+ has it built in).");
    this.fetchImpl = f.bind(globalThis);
  }

  async request<T>(spec: RequestSpec, options: RequestOptions = {}): Promise<T> {
    const rawPath = spec.path.replace(/\{(\w+)\}/g, (_, name: string) => {
      const value = spec.pathParams?.[name];
      if (value === undefined || value === "") throw new TypeError(`SigWise: ${name} is required`);
      return String(value);
    });
    const encodedPath = spec.path.replace(/\{(\w+)\}/g, (_, name: string) =>
      encodeURIComponent(String(spec.pathParams?.[name])),
    );
    const url = new URL(this.baseUrl + encodedPath);
    url.searchParams.set("api_key", this.apiKey);
    for (const [key, value] of Object.entries(spec.query ?? {})) {
      if (value === undefined || value === null) continue;
      for (const v of Array.isArray(value) ? value : [value]) {
        url.searchParams.append(key, v instanceof Date ? v.toISOString() : String(v));
      }
    }

    const method = spec.method.toUpperCase();
    const maxRetries = IDEMPOTENT.has(method) ? (options.maxRetries ?? this.maxRetries) : 0;
    const body = spec.body === undefined ? undefined : JSON.stringify(spec.body);

    for (let attempt = 0; ; attempt++) {
      const headers: Record<string, string> = {
        Accept: "application/json",
        "User-Agent": `@sigwise/node/${VERSION} (node)`,
        ...this.headers,
        ...options.headers,
        Authorization: `Bearer ${signRequestToken(this.apiKey, this.secret, method, rawPath)}`,
      };
      if (body !== undefined) headers["Content-Type"] = "application/json";

      let response: Response;
      try {
        response = await this.send(url, { method, headers, body }, options);
      } catch (err) {
        if (options.signal?.aborted || attempt >= maxRetries) {
          throw new SigWiseConnectionError(`SigWise: ${method} ${rawPath} failed: ${(err as Error).message}`, { cause: err });
        }
        await sleep(backoff(attempt));
        continue;
      }

      if (response.ok) return (await decode(response)) as T;
      if (attempt < maxRetries && RETRY_STATUSES.has(response.status)) {
        await sleep(backoff(attempt, response.headers.get("retry-after")));
        continue;
      }
      const errBody = await decode(response);
      const err = (errBody as { error?: { code?: string; message?: string } } | undefined)?.error;
      throw new SigWiseError(
        response.status,
        err?.code ?? "http_" + response.status,
        err?.message ?? `${method} ${rawPath} returned ${response.status}`,
        errBody,
        response.headers,
      );
    }
  }

  private async send(url: URL, init: RequestInit, options: RequestOptions): Promise<Response> {
    const controller = new AbortController();
    const timeout = options.timeout ?? this.timeout;
    const timer = setTimeout(() => controller.abort(new Error(`timed out after ${timeout}ms`)), timeout);
    const onAbort = () => controller.abort(options.signal?.reason);
    options.signal?.addEventListener("abort", onAbort, { once: true });
    try {
      return await this.fetchImpl(url, { ...init, signal: controller.signal });
    } finally {
      clearTimeout(timer);
      options.signal?.removeEventListener("abort", onAbort);
    }
  }
}

async function decode(response: Response): Promise<unknown> {
  if (response.status === 204) return undefined;
  const text = await response.text();
  if (!text) return undefined;
  if ((response.headers.get("content-type") ?? "").includes("json")) {
    try {
      return JSON.parse(text);
    } catch {
      return text;
    }
  }
  return text;
}

function backoff(attempt: number, retryAfter?: string | null): number {
  const seconds = retryAfter ? Number(retryAfter) : NaN;
  if (Number.isFinite(seconds) && seconds >= 0) return Math.min(seconds * 1000, 60_000);
  const base = Math.min(500 * 2 ** attempt, 8_000);
  return base / 2 + Math.random() * (base / 2);
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
