// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

import { Core, type ClientOptions } from "./core.js";
import { MeResource, OverviewResource, ObjectsResource, EventsResource, SignalsResource, SettingsResource, WebhooksResource, WebhookDeliveriesResource, RulesResource, RuleFiringsResource, ApiKeysResource, BillingResource, UsageResource } from "./resources.js";

export * from "./models.js";
export * from "./resources.js";
export * from "./webhooks.js";
export { SigWiseConnectionError, SigWiseError, DEFAULT_BASE_URL, VERSION, signRequestToken } from "./core.js";
export type { ClientOptions, RequestOptions } from "./core.js";

/**
 * SigWise API client. Send events about your objects, get typed answers back.
 *
 * @example
const sigwise = new SigWise({ apiKey: "your_key_id", secret: "your_secret" });
 */
export class SigWise {
  /** The authenticated principal and tenant settings. */
  readonly me: MeResource;
  /** An object is anything you want answers about: a user, a listing, an order. */
  readonly overview: OverviewResource;
  /** An object is anything you want answers about: a user, a listing, an order. */
  readonly objects: ObjectsResource;
  /** Events and messages are the evidence an object's answers are computed from. */
  readonly events: EventsResource;
  /**
   * A signal is a question you ask about every object, such as "is this a scammer?"
   * (`noul`), "how trustworthy is this user?" (`score`) or "what is their buyer intent?"
   * (`choice`).
   */
  readonly signals: SignalsResource;
  /** The authenticated principal and tenant settings. */
  readonly settings: SettingsResource;
  /**
   * Webhook endpoints receive a signed `POST` for the event types they subscribe to:
   * `analysis.completed` each time an analysis completes, and `rule.triggered` when a rule
   * with a webhook action fires.
   */
  readonly webhooks: WebhooksResource;
  /**
   * Webhook endpoints receive a signed `POST` for the event types they subscribe to:
   * `analysis.completed` each time an analysis completes, and `rule.triggered` when a rule
   * with a webhook action fires.
   */
  readonly webhookDeliveries: WebhookDeliveriesResource;
  /**
   * A rule fires an action (email, Slack or webhook) when an object's signal values cross a
   * line you care about, such as `is_scammer >= 90`.
   */
  readonly rules: RulesResource;
  /**
   * A rule fires an action (email, Slack or webhook) when an object's signal values cross a
   * line you care about, such as `is_scammer >= 90`.
   */
  readonly ruleFirings: RuleFiringsResource;
  /** Create, rotate and revoke the keys your integrations sign requests with. */
  readonly apiKeys: ApiKeysResource;
  /** Prepaid balance, the billing ledger, and card top-ups. */
  readonly billing: BillingResource;
  /** Analysis volume, spend and token usage over a date range. */
  readonly usage: UsageResource;

  constructor(options: ClientOptions = {}) {
    const core = new Core(options);
    this.me = new MeResource(core);
    this.overview = new OverviewResource(core);
    this.objects = new ObjectsResource(core);
    this.events = new EventsResource(core);
    this.signals = new SignalsResource(core);
    this.settings = new SettingsResource(core);
    this.webhooks = new WebhooksResource(core);
    this.webhookDeliveries = new WebhookDeliveriesResource(core);
    this.rules = new RulesResource(core);
    this.ruleFirings = new RuleFiringsResource(core);
    this.apiKeys = new ApiKeysResource(core);
    this.billing = new BillingResource(core);
    this.usage = new UsageResource(core);
  }
}

export default SigWise;
