// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

export interface ApiKey {
  id: string;
  /** The public key ID, sent as `api_key`. */
  key: string;
  name: string;
  status: ApiKeyStatus;
  /** Whether the key can sign requests. Legacy keys can't until rotated. */
  has_secret: boolean;
  /** Created before request signing; rotate it to get a signing secret. */
  legacy?: boolean;
  legacy_preview?: string;
  created_at: string;
  last_used_at?: string;
  legacy_used_at?: string;
}

export interface ApiKeyCreate {
  name?: string;
}

export interface ApiKeyList {
  api_keys: ApiKey[];
}

export interface ApiKeySecret {
  api_key: ApiKey;
  /** The public key ID. */
  key: string;
  /** The signing secret. Shown only once. */
  secret: string;
  note: string;
}

export type ApiKeyStatus = "active" | "inactive" | "revoked";

export interface ApiKeyUpdate {
  name?: string;
  status?: "active" | "inactive";
}

/**
 * Depends on `action_type`:
 *
 * - `email`: `{"to": "abuse@acme.com", "subject": "…"}` (`subject` optional)
 * - `slack`: `{"webhook_url": "https://hooks.slack.com/…"}`
 * - `webhook`: `{"endpoint_id": "<registered endpoint id>"}`
 */
export type ActionConfig = Record<string, unknown>;

export type ActionType = "email" | "slack" | "webhook";

export interface AnalysisCompletedEvent {
  event: "analysis.completed";
  object_id: string;
  tenant_id: string;
  model: string;
  occurred_at: string;
  answers: Answer[];
}

export interface AnalyzeAllScheduled {
  /** How many objects were scheduled. */
  scheduled: number;
  analysis_status: "scheduled";
}

export interface AnalyzeScheduled {
  object_id: string;
  analysis_status: "scheduled";
}

/** One signal's answer. Only the fields for its `type` are set. */
export interface Answer {
  signal: string;
  /** `noul`: yes/no probability. */
  type: SignalType;
  /** `noul`: the probability the answer is yes. */
  noul?: number;
  /** `choice`: the most likely option. */
  choice?: string;
  /**
   * `score`: the position on the spectrum, from 0 (the first level) to the number of levels
   * minus one.
   */
  score?: number;
  /** `choice` and `score`: the probability of each option or level. */
  probabilities?: Record<string, number>;
  /** `choice` and `score`: the analyzer's confidence. */
  confidence?: number;
}

export interface BackfillEstimate {
  /** Objects with no answer for the signal. */
  objects: number;
  /** Estimated cost in micro-dollars (1e-6 USD), an upper bound. 0 without paid history. */
  estimated_cost_micros: number;
}

export interface BackfillStatus {
  estimate: BackfillEstimate;
  backfill: SignalBackfill | null;
}

export interface Balance {
  balance_cents: number;
  currency: string;
  /** Whether analyses are billed on this deployment. */
  metering_enabled: boolean;
  /** `block` pauses analyses at an empty balance; `grace` lets it go negative. */
  enforcement: string;
  /** Whether card top-ups are available. */
  self_serve_topup: boolean;
  low_balance_threshold_cents: number;
  topup_min_cents?: number;
  topup_max_cents?: number;
}

/** How many objects have one `object_type`. */
export interface CategoryCount {
  name: string;
  count: number;
}

export interface CheckoutCreate {
  /** Within the deployment's `topup_min_cents`–`topup_max_cents`. */
  amount_cents: number;
}

export interface CheckoutSession {
  id: string;
  /** Send the customer here to pay. */
  url: string;
}

export interface CheckoutStatus {
  id: string;
  status: "pending" | "credited";
  amount_cents?: number;
  balance_after_cents?: number;
}

/** A rolling summary of an object's older events. */
export interface CompactedState {
  total_events: number;
  messages: number;
  actions: number;
  by_action?: Record<string, number>;
  sample_messages?: string[];
  first_seen: string;
  updated_at: string;
}

/** `dead` deliveries are in the dead-letter queue: permanently rejected, or out of retries. */
export type DeliveryStatus = "pending" | "delivering" | "delivered" | "dead";

export interface Event {
  /** `event` is a discrete action (e.g. */
  type: EventType;
  name?: string;
  content?: string;
  /** Arbitrary structured attributes. */
  metadata?: Metadata;
  occurred_at: string;
}

export interface EventInput {
  /** `event` is a discrete action (e.g. */
  type: EventType;
  /** The event name, or a message's subject. */
  name?: string;
  /** Free text, such as a message body. */
  content?: string;
  /** Arbitrary structured attributes. */
  metadata?: Metadata;
  /** When it happened. Defaults to the time the API received it. */
  occurred_at?: string;
}

export interface EventList {
  events: Event[];
}

/** `event` is a discrete action (e.g. `profile.updated`); `message` is free-form text. */
export type EventType = "event" | "message";

export interface IngestAccepted {
  object_id: string;
  /** How many events were recorded. */
  accepted: number;
  analysis_status: "scheduled";
  /** The debounce window before the analysis runs. */
  analysis_delay_ms: number;
}

export interface IngestRequest {
  /** Optional classification, e.g. `user` or `listing`. */
  object_type?: string;
  events: EventInput[];
  /**
   * Score the object inline and return the verdict (`200`) instead of scheduling analysis
   * (`202`).
   */
  wait?: boolean;
  /** With `wait`, score only these signal keys. Ignored otherwise. */
  signals?: string[];
  /**
   * With `wait`, whether to score over the object's prior history (`true`) or only this
   * request's events (`false`).
   */
  include_history?: boolean;
}

export interface LedgerEntry {
  id: string;
  /**
   * Negative for a charge, positive for a credit. Sub-cent charges round to 0; see
   * `delta_micros`.
   */
  delta_cents: number;
  balance_after_cents: number;
  /** The exact amount in micro-dollars (1e-6 USD). */
  delta_micros: number;
  balance_after_micros: number;
  reason: string;
  model?: string;
  object_id?: string;
  cost_usd?: number;
  cost_margin?: number;
  input_tokens?: number;
  output_tokens?: number;
  /** The Stripe Checkout Session that paid for a top-up. */
  payment_ref?: string;
  created_at: string;
}

export interface LedgerPage {
  entries: LedgerEntry[];
  /** Pass as `cursor` for the next page. Empty on the last page. */
  next_cursor: string;
}

export interface Me {
  /** `tenant` for API keys, `console` for a signed-in user. */
  auth_type: "tenant" | "console";
  tenant_id: string;
  tenant_name: string;
  user_id?: string;
  email?: string;
  role?: string;
  onboarded?: boolean;
}

/** Arbitrary structured attributes. */
export type Metadata = Record<string, unknown>;

export interface ModerationVerdict {
  object_id: string;
  /** How many events were recorded. */
  accepted: number;
  /** False when no configured signal matched, so nothing was scored. */
  analyzed: boolean;
  history_included: boolean;
  /** The model that produced the answers, e.g. `model-1`. */
  model: string;
  latency_ms: number;
  answers: Answer[];
  /** Why nothing was analyzed, when `analyzed` is false. */
  reason?: string;
}

export interface ObjectAnalysis {
  object_id: string;
  event_count: number;
  analysis: SignalResult[];
  /** Enabled signals with no answer yet. */
  pending: string[];
}

export interface ObjectList {
  objects: ObjectSummary[];
  limit: number;
  offset: number;
  /** Pass as `cursor` to fetch the next page. Absent on the last page and for signal queries. */
  next_cursor?: string;
}

export interface ObjectState {
  object_id: string;
  /** How many events have been folded into the summary. */
  compacted_events: number;
  compacted_through?: string | null;
  compacted_state?: CompactedState | null;
  last_analyzed_at?: string | null;
}

export interface ObjectSummary {
  object_id: string;
  object_type: string;
  display_name?: string;
  event_count: number;
  last_seen: string;
  analysis: SignalResult[];
  pending: string[];
}

export interface Overview {
  objects: number;
  signals: number;
  /** Share of objects with at least one answer, 0–1. */
  analyzed_pct: number;
  /** Events recorded in the last 24 hours. */
  events_today: number;
  flagged: number;
  signal_summary: SignalSummary[];
  categories: CategoryCount[];
  top_risk: RiskyObject[];
}

/** One of the objects with the highest yes/no probabilities. */
export interface RiskyObject {
  object_id: string;
  display_name?: string;
  risk: number;
}

export interface Rule {
  id: string;
  name: string;
  /** The condition, e.g. `is_scammer >= 90 and trust_score < 1`. */
  when: string;
  action_type: ActionType;
  /**
   * Depends on `action_type`: - `email`: `{"to": "abuse@acme.com", "subject": "…"}`
   * (`subject` optional) - `slack`: `{"webhook_url": "https://hooks.slack.com/…"}` -
   * `webhook`: `{"endpoint_id": "<registered endpoint id>"}`
   */
  action_config: ActionConfig;
  enabled: boolean;
  /**
   * 0 fires only when the condition turns true; more lets the rule re-fire after that long
   * while it stays true.
   */
  cooldown_seconds: number;
  created_at: string;
  updated_at: string;
}

export interface RuleCreate {
  name?: string;
  when: string;
  action_type: ActionType;
  /**
   * Depends on `action_type`: - `email`: `{"to": "abuse@acme.com", "subject": "…"}`
   * (`subject` optional) - `slack`: `{"webhook_url": "https://hooks.slack.com/…"}` -
   * `webhook`: `{"endpoint_id": "<registered endpoint id>"}`
   */
  action_config: ActionConfig;
  enabled?: boolean;
  cooldown_seconds?: number;
}

export interface RuleFiring {
  id: string;
  rule_id: string;
  object_id: string;
  matched_when: string;
  /** The signal values that satisfied the condition. */
  signal_values?: Record<string, unknown>;
  action_type: ActionType;
  status: "dispatched" | "error";
  /** The error, or a short success note. */
  detail?: string;
  fired_at: string;
}

export interface RuleFiringList {
  firings: RuleFiring[];
}

export interface RuleList {
  rules: Rule[];
}

export interface RuleTriggeredEvent {
  event: "rule.triggered";
  rule_id: string;
  rule_name?: string;
  tenant_id: string;
  object_id: string;
  matched_when: string;
  model?: string;
  occurred_at: string;
  values: Answer[];
}

export interface RuleUpdate {
  name?: string;
  when?: string;
  action_type?: ActionType;
  /**
   * Depends on `action_type`: - `email`: `{"to": "abuse@acme.com", "subject": "…"}`
   * (`subject` optional) - `slack`: `{"webhook_url": "https://hooks.slack.com/…"}` -
   * `webhook`: `{"endpoint_id": "<registered endpoint id>"}`
   */
  action_config?: ActionConfig;
  enabled?: boolean;
  cooldown_seconds?: number;
}

export interface Settings {
  /**
   * Creating a signal automatically backfills existing objects for it. Off by default
   * because each analysis is billed.
   */
  auto_backfill_signals: boolean;
}

export interface SettingsUpdate {
  auto_backfill_signals?: boolean;
}

export interface Signal {
  key: string;
  /** `noul`: yes/no probability. */
  type: SignalType;
  instructions: unknown;
  criteria?: unknown;
  enabled: boolean;
  created_at: string;
  updated_at: string;
  /** Set only when creating the signal started a backfill (`auto_backfill_signals`). */
  backfill?: SignalBackfill;
}

export interface SignalBackfill {
  signal_key: string;
  status: "running" | "done";
  /** Objects enqueued when the backfill started. */
  total: number;
  /** Objects answered since it started. */
  completed: number;
  /** Objects still queued or running. */
  pending: number;
  started_at: string;
}

export interface SignalInput {
  /** `noul`: yes/no probability. */
  type: SignalType;
  /**
   * What the analyzer should decide. Usually a string; objects and arrays are passed through
   * verbatim.
   */
  instructions: unknown;
  /** Depends on `type`; see the operation description. */
  criteria?: unknown;
  enabled?: boolean;
}

export interface SignalList {
  signals: Signal[];
}

/** The latest answer for one signal. Only the fields for its `type` are set. */
export interface SignalResult {
  key: string;
  /** `noul`: yes/no probability. */
  type: SignalType;
  noul?: number;
  choice?: string;
  score?: number;
  probabilities?: Record<string, number>;
  confidence?: number;
  model?: string;
  computed_at: string;
}

export interface SignalSummary {
  key: string;
  /** `noul`: yes/no probability. */
  type: SignalType;
  /** Objects with an answer for the signal. */
  total: number;
  avg?: number;
  /** Objects answered high (yes/no signals). */
  high?: number;
  high_pct?: number;
  /** `choice` signals: the share of each option. */
  choices?: Record<string, number>;
}

/**
 * `noul`: yes/no probability. `score`: position on a labelled spectrum. `choice`: one of N
 * options.
 */
export type SignalType = "noul" | "choice" | "score";

export interface Usage {
  from: string;
  to: string;
  currency: string;
  metering_enabled: boolean;
  balance_cents: number;
  /** Average spend per elapsed day of the range, in micro-dollars. */
  burn_rate_micros_per_day: number;
  /** Balance divided by burn rate. Omitted without spend or balance. */
  runway_days?: number;
  totals: UsageTotals;
  series: UsageDay[];
  by_model: UsageBreakdown[];
  by_source: UsageBreakdown[];
  by_signal: UsageSignal[];
}

export interface UsageBreakdown {
  key: string;
  analyses: number;
  spend_micros: number;
  input_tokens: number;
  output_tokens: number;
}

export interface UsageDay {
  date: string;
  analyses: number;
  async: number;
  sync: number;
  spend_micros: number;
}

export interface UsageSignal {
  signal: string;
  analyses: number;
}

export interface UsageTotals {
  analyses: number;
  spend_micros: number;
  input_tokens: number;
  output_tokens: number;
}

export interface WebhookDelivery {
  id: string;
  endpoint_id: string;
  event_type: "analysis.completed" | "rule.triggered";
  object_id?: string;
  /** `dead` deliveries are in the dead-letter queue: permanently rejected, or out of retries. */
  status: DeliveryStatus;
  attempts: number;
  max_attempts: number;
  /** The endpoint's last HTTP status, if it answered. */
  last_status_code?: number;
  last_error?: string;
  /** When the next attempt is due. */
  run_after: string;
  delivered_at?: string;
  created_at: string;
  /** The body that is (or was) delivered. */
  payload?: Record<string, unknown>;
}

export interface WebhookDeliveryList {
  deliveries: WebhookDelivery[];
}

export interface WebhookEndpoint {
  id: string;
  url: string;
  description: string;
  enabled: boolean;
  /** Only deliver analyses that answered one of these signals. Empty means every analysis. */
  signal_keys: string[];
  /** The event types this endpoint receives. */
  events: WebhookEventType[];
  created_at: string;
  updated_at: string;
}

export interface WebhookEndpointCreate {
  /** An `http` or `https` URL. */
  url: string;
  description?: string;
  signal_keys?: string[];
  /**
   * The event types to deliver. Omit to receive every event type. Use `["rule.triggered"]`
   * for an endpoint that only receives rule firings.
   */
  events?: WebhookEventType[];
  enabled?: boolean;
}

export interface WebhookEndpointCreated {
  endpoint: WebhookEndpoint;
  /** The signing secret. Shown only once. */
  secret: string;
  note: string;
}

export interface WebhookEndpointList {
  webhooks: WebhookEndpoint[];
}

export interface WebhookEndpointUpdate {
  url?: string;
  description?: string;
  signal_keys?: string[];
  events?: WebhookEventType[];
  enabled?: boolean;
}

export type WebhookEventType = "analysis.completed" | "rule.triggered";

/** A webhook delivery's body. Switch on `event` to narrow it. */
export type WebhookEvent = AnalysisCompletedEvent | RuleTriggeredEvent;
