// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

import type { Core, RequestOptions } from "./core.js";
import type * as T from "./models.js";

/** Query parameters of `objects.list`. */
export interface ListObjectsParams {
  /**
   * Substring search, or a signal query like `is_scammer >= 90, buyer_intent =
   * ready_to_buy`.
   */
  q?: string;
  /**
   * `recent` (last seen first, the default), `flagged` (highest yes/no probability first) or
   * `trust` (highest score first).
   */
  sort?: "recent" | "flagged" | "trust";
  limit?: number;
  /** Rows to skip. Prefer `cursor` for deep pages; offsets get slower the further they go. */
  offset?: number;
  /**
   * The `next_cursor` of the previous page. Pages by position rather than offset, so every
   * page is equally fast; `offset` is ignored when set. Keep `q` and `sort` the same across
   * pages. Signal queries page by `offset` only.
   */
  cursor?: string;
}

/** Query parameters of `webhookDeliveries.list`. */
export interface ListWebhookDeliveriesParams {
  status?: T.DeliveryStatus;
  endpoint_id?: string;
  limit?: number;
}

/** Query parameters of `ruleFirings.list`. */
export interface ListRuleFiringsParams {
  rule_id?: string;
  object_id?: string;
  limit?: number;
}

/** Query parameters of `billing.listLedger`. */
export interface ListLedgerParams {
  /** Only credits (funds added) or only charges (analyses). */
  type?: "credit" | "charge";
  limit?: number;
  /** `batch` lists each bulk run once, as its newest charge with the run's totals in `batch`. */
  group?: "batch";
  /** Only the charges of this bulk run. */
  batch_id?: string;
  cursor?: string;
}

/** Query parameters of `usage.get`. */
export interface GetUsageParams {
  /** First day, `YYYY-MM-DD`. Defaults to 29 days before `to`. */
  from?: string;
  /** Last day, `YYYY-MM-DD`. Defaults to today. */
  to?: string;
}

/** The authenticated principal and tenant settings. */
export class MeResource {
  constructor(private readonly core: Core) {}

  /**
   * Get the current principal.
   *
   * Returns the tenant the credential belongs to. For console tokens it also returns the
   * signed-in user and whether they finished onboarding.
   *
   * `GET /v1/me`
   */
  get(options?: RequestOptions): Promise<T.Me> {
    return this.core.request<T.Me>(
      {
        method: "GET",
        path: "/v1/me",
      },
      options,
    );
  }
}

/** An object is anything you want answers about: a user, a listing, an order. */
export class OverviewResource {
  constructor(private readonly core: Core) {}

  /**
   * Get tenant overview.
   *
   * Tenant-wide totals and per-signal value distributions, computed with SQL aggregates.
   *
   * `GET /v1/overview`
   */
  get(options?: RequestOptions): Promise<T.Overview> {
    return this.core.request<T.Overview>(
      {
        method: "GET",
        path: "/v1/overview",
      },
      options,
    );
  }
}

/** An object is anything you want answers about: a user, a listing, an order. */
export class ObjectsResource {
  constructor(private readonly core: Core) {}

  /**
   * Re-analyze every object.
   *
   * Schedules a re-analysis of every object the tenant has, typically after changing signal
   * configuration. Jobs run at bulk priority, behind live traffic. Each analysis is billed.
   *
   * `POST /v1/analyze`
   */
  analyzeAll(options?: RequestOptions): Promise<T.AnalyzeAllScheduled> {
    return this.core.request<T.AnalyzeAllScheduled>(
      {
        method: "POST",
        path: "/v1/analyze",
      },
      options,
    );
  }

  /**
   * List objects.
   *
   * Returns one page of objects with their latest analysis.
   *
   * `q` is either a substring of the object ID or display name, or a signal query such as
   * `is_scammer > 90 and trust_score < 1` (see [Search and
   * conditions](https://sigwise.ai/docs/guides/queries)).
   *
   * `GET /v1/objects`
   */
  list(params?: ListObjectsParams, options?: RequestOptions): Promise<T.ObjectList> {
    return this.core.request<T.ObjectList>(
      {
        method: "GET",
        path: "/v1/objects",
        query: params,
      },
      options,
    );
  }

  /**
   * Get an object's analysis.
   *
   * Returns the latest answer for each signal computed for the object, plus the configured
   * signals that have no answer yet (`pending`).
   *
   * Reads are cached for a few seconds; the `X-Cache` header says whether this one was a
   * `HIT` or a `MISS`. Ingesting events and completed analyses invalidate the cache.
   *
   * `GET /v1/objects/{object_id}`
   */
  get(objectId: string, options?: RequestOptions): Promise<T.ObjectAnalysis> {
    return this.core.request<T.ObjectAnalysis>(
      {
        method: "GET",
        path: "/v1/objects/{object_id}",
        pathParams: { object_id: objectId },
      },
      options,
    );
  }

  /**
   * Get an object's compacted history.
   *
   * Older events are folded into a rolling summary so the analyzer gets a bounded payload
   * while keeping long-term signal. This returns that summary and the compaction cursor.
   *
   * `GET /v1/objects/{object_id}/state`
   */
  getState(objectId: string, options?: RequestOptions): Promise<T.ObjectState> {
    return this.core.request<T.ObjectState>(
      {
        method: "GET",
        path: "/v1/objects/{object_id}/state",
        pathParams: { object_id: objectId },
      },
      options,
    );
  }

  /**
   * Re-analyze an object.
   *
   * Schedules an immediate re-analysis without a new event, for example right after adding a
   * signal. Runs at live priority; poll `GET /v1/objects/{object_id}` for the result.
   * Returns `404` when the object has no events.
   *
   * `POST /v1/objects/{object_id}/analyze`
   */
  analyze(objectId: string, options?: RequestOptions): Promise<T.AnalyzeScheduled> {
    return this.core.request<T.AnalyzeScheduled>(
      {
        method: "POST",
        path: "/v1/objects/{object_id}/analyze",
        pathParams: { object_id: objectId },
      },
      options,
    );
  }
}

/** Events and messages are the evidence an object's answers are computed from. */
export class PlaygroundResource {
  constructor(private readonly core: Core) {}

  /**
   * Try signals on sample events.
   *
   * Scores sample events against your enabled signals and returns the answers, **without
   * recording anything**: no object is created, the events and answers are not stored, and
   * no rule or webhook fires. Use it to check how your signals judge content before you send
   * real traffic, or after you change a signal's instructions.
   *
   * The events are scored on their own, with no history. Restrict the run to some signals
   * with `signals`. At most 50 events per run.
   *
   * The analysis is real, so it is charged to your balance like any other and counted as a
   * synchronous analysis in your usage. Returns `402` when the balance is empty, `429` when
   * the account already has the maximum number of synchronous analyses in flight, and `503`
   * with `analyzer_busy` when the analyzer is throttling.
   *
   * `POST /v1/playground`
   */
  run(body: T.PlaygroundRequest, options?: RequestOptions): Promise<T.PlaygroundResult> {
    return this.core.request<T.PlaygroundResult>(
      {
        method: "POST",
        path: "/v1/playground",
        body,
      },
      options,
    );
  }
}

/** Events and messages are the evidence an object's answers are computed from. */
export class EventsResource {
  constructor(private readonly core: Core) {}

  /**
   * Ingest events.
   *
   * Records one or more events or messages about an object.
   *
   * **Asynchronous (default).** Returns `202` immediately and schedules a debounced
   * analysis: a burst of events for one object coalesces into a single analysis once
   * activity settles. Read the answers with `GET /v1/objects/{object_id}` or receive them by
   * webhook.
   *
   * **Synchronous (`wait: true`).** Blocks on the analyzer and returns the verdict inline
   * with `200`, so you can approve, review or block content before publishing it. Restrict
   * scoring to some signals with `signals`, and score the request's events in isolation with
   * `include_history: false`.
   *
   * Returns `402` when the tenant's balance is empty. A synchronous request returns `429`
   * when the account already has the maximum number of synchronous analyses in flight (8 by
   * default), and `503` with `analyzer_busy` when the analyzer is throttling; the events are
   * recorded either way, so don't resend them: after `Retry-After`, request an analysis with
   * `POST /v1/objects/{object_id}/analyze` and read the answers with `GET
   * /v1/objects/{object_id}` or by webhook.
   *
   * **Safe retries.** Send an `Idempotency-Key` header (any unique string, such as a UUID)
   * and retry with the same key after a timeout or a `5xx`: the events are recorded once. A
   * repeat of an asynchronous request is answered like the first and carries
   * `Idempotent-Replayed: true`. A repeat of a synchronous request returns `409` without
   * analyzing (or charging) again; read the verdict with `GET /v1/objects/{object_id}`.
   * Reusing a key for a different object returns `422`. Keys are remembered for 24 hours.
   *
   * `POST /v1/objects/{object_id}/events`
   */
  ingest(objectId: string, body: T.IngestRequest, options?: RequestOptions): Promise<T.ModerationVerdict | T.IngestAccepted> {
    return this.core.request<T.ModerationVerdict | T.IngestAccepted>(
      {
        method: "POST",
        path: "/v1/objects/{object_id}/events",
        pathParams: { object_id: objectId },
        body,
      },
      options,
    );
  }

  /**
   * List an object's events.
   *
   * Returns up to the 200 most recent events and messages recorded for the object, newest
   * first.
   *
   * `GET /v1/objects/{object_id}/events`
   */
  list(objectId: string, options?: RequestOptions): Promise<T.EventList> {
    return this.core.request<T.EventList>(
      {
        method: "GET",
        path: "/v1/objects/{object_id}/events",
        pathParams: { object_id: objectId },
      },
      options,
    );
  }
}

/**
 * A signal is a question you ask about every object, such as "is this a scammer?"
 * (`noul`), "how trustworthy is this user?" (`score`) or "what is their buyer intent?"
 * (`choice`).
 */
export class SignalsResource {
  constructor(private readonly core: Core) {}

  /**
   * List signals.
   *
   * `GET /v1/signals`
   */
  list(options?: RequestOptions): Promise<T.SignalList> {
    return this.core.request<T.SignalList>(
      {
        method: "GET",
        path: "/v1/signals",
      },
      options,
    );
  }

  /**
   * Create or update a signal.
   *
   * Creates the signal, or replaces its definition. `instructions` and `criteria` are passed
   * to the analyzer verbatim; the shape of `criteria` depends on `type`:
   *
   * | `type` | `criteria` |
   * |----------|------------------------------------------------------|
   * | `noul` | object with optional `true` / `false` descriptions |
   * | `score` | ordered array of level descriptions, low to high |
   * | `choice` | object mapping each option to a description or null |
   *
   * Creating a signal does not analyze existing objects unless the tenant setting
   * `auto_backfill_signals` is on; start a backfill explicitly with `POST
   * /v1/signals/{key}/backfill`.
   *
   * `PUT /v1/signals/{key}`
   */
  upsert(key: string, body: T.SignalInput, options?: RequestOptions): Promise<T.Signal> {
    return this.core.request<T.Signal>(
      {
        method: "PUT",
        path: "/v1/signals/{key}",
        pathParams: { key: key },
        body,
      },
      options,
    );
  }

  /**
   * Delete a signal.
   *
   * `DELETE /v1/signals/{key}`
   */
  delete(key: string, options?: RequestOptions): Promise<void> {
    return this.core.request<void>(
      {
        method: "DELETE",
        path: "/v1/signals/{key}",
        pathParams: { key: key },
      },
      options,
    );
  }

  /**
   * Get backfill estimate and progress.
   *
   * Returns how many existing objects have no answer for the signal and what analyzing them
   * would cost now, plus the progress of the most recent backfill (`null` if none was
   * started).
   *
   * `GET /v1/signals/{key}/backfill`
   */
  getBackfill(key: string, options?: RequestOptions): Promise<T.BackfillStatus> {
    return this.core.request<T.BackfillStatus>(
      {
        method: "GET",
        path: "/v1/signals/{key}/backfill",
        pathParams: { key: key },
      },
      options,
    );
  }

  /**
   * Start a backfill.
   *
   * Re-analyzes, for this signal only, every existing object that has no answer for it. Jobs
   * run at bulk priority so they never delay live ingest. Each analysis is billed. Returns
   * `409` if the signal is disabled.
   *
   * `POST /v1/signals/{key}/backfill`
   */
  startBackfill(key: string, options?: RequestOptions): Promise<T.SignalBackfill> {
    return this.core.request<T.SignalBackfill>(
      {
        method: "POST",
        path: "/v1/signals/{key}/backfill",
        pathParams: { key: key },
      },
      options,
    );
  }
}

/** The authenticated principal and tenant settings. */
export class SettingsResource {
  constructor(private readonly core: Core) {}

  /**
   * Get tenant settings.
   *
   * `GET /v1/settings`
   */
  get(options?: RequestOptions): Promise<T.Settings> {
    return this.core.request<T.Settings>(
      {
        method: "GET",
        path: "/v1/settings",
      },
      options,
    );
  }

  /**
   * Update tenant settings.
   *
   * Omitted fields are left unchanged.
   *
   * `PATCH /v1/settings`
   */
  update(body: T.SettingsUpdate, options?: RequestOptions): Promise<T.Settings> {
    return this.core.request<T.Settings>(
      {
        method: "PATCH",
        path: "/v1/settings",
        body,
      },
      options,
    );
  }
}

/**
 * Webhook endpoints receive a signed `POST` for the event types they subscribe to:
 * `analysis.completed` each time an analysis completes, and `rule.triggered` when a rule
 * with a webhook action fires.
 */
export class WebhooksResource {
  constructor(private readonly core: Core) {}

  /**
   * List webhook endpoints.
   *
   * `GET /v1/webhooks`
   */
  list(options?: RequestOptions): Promise<T.WebhookEndpointList> {
    return this.core.request<T.WebhookEndpointList>(
      {
        method: "GET",
        path: "/v1/webhooks",
      },
      options,
    );
  }

  /**
   * Register a webhook endpoint.
   *
   * Registers an endpoint and returns its signing secret. **The secret is shown only once**;
   * store it to verify deliveries.
   *
   * `POST /v1/webhooks`
   */
  create(body: T.WebhookEndpointCreate, options?: RequestOptions): Promise<T.WebhookEndpointCreated> {
    return this.core.request<T.WebhookEndpointCreated>(
      {
        method: "POST",
        path: "/v1/webhooks",
        body,
      },
      options,
    );
  }

  /**
   * Get a webhook endpoint.
   *
   * `GET /v1/webhooks/{endpoint_id}`
   */
  get(endpointId: string, options?: RequestOptions): Promise<T.WebhookEndpoint> {
    return this.core.request<T.WebhookEndpoint>(
      {
        method: "GET",
        path: "/v1/webhooks/{endpoint_id}",
        pathParams: { endpoint_id: endpointId },
      },
      options,
    );
  }

  /**
   * Update a webhook endpoint.
   *
   * Omitted fields are left unchanged.
   *
   * `PATCH /v1/webhooks/{endpoint_id}`
   */
  update(endpointId: string, body: T.WebhookEndpointUpdate, options?: RequestOptions): Promise<T.WebhookEndpoint> {
    return this.core.request<T.WebhookEndpoint>(
      {
        method: "PATCH",
        path: "/v1/webhooks/{endpoint_id}",
        pathParams: { endpoint_id: endpointId },
        body,
      },
      options,
    );
  }

  /**
   * Delete a webhook endpoint.
   *
   * Removes the endpoint and its deliveries.
   *
   * `DELETE /v1/webhooks/{endpoint_id}`
   */
  delete(endpointId: string, options?: RequestOptions): Promise<void> {
    return this.core.request<void>(
      {
        method: "DELETE",
        path: "/v1/webhooks/{endpoint_id}",
        pathParams: { endpoint_id: endpointId },
      },
      options,
    );
  }
}

/**
 * Webhook endpoints receive a signed `POST` for the event types they subscribe to:
 * `analysis.completed` each time an analysis completes, and `rule.triggered` when a rule
 * with a webhook action fires.
 */
export class WebhookDeliveriesResource {
  constructor(private readonly core: Core) {}

  /**
   * List webhook deliveries.
   *
   * Recent deliveries, newest first. Filter with `status=dead` to inspect the dead-letter
   * queue.
   *
   * `GET /v1/webhook_deliveries`
   */
  list(params?: ListWebhookDeliveriesParams, options?: RequestOptions): Promise<T.WebhookDeliveryList> {
    return this.core.request<T.WebhookDeliveryList>(
      {
        method: "GET",
        path: "/v1/webhook_deliveries",
        query: params,
      },
      options,
    );
  }

  /**
   * Replay a delivery.
   *
   * Re-queues a delivery (for example one in the dead-letter queue) for another attempt.
   *
   * `POST /v1/webhook_deliveries/{delivery_id}/replay`
   */
  replay(deliveryId: string, options?: RequestOptions): Promise<T.WebhookDelivery> {
    return this.core.request<T.WebhookDelivery>(
      {
        method: "POST",
        path: "/v1/webhook_deliveries/{delivery_id}/replay",
        pathParams: { delivery_id: deliveryId },
      },
      options,
    );
  }
}

/**
 * A rule fires an action (email, Slack or webhook) when an object's signal values cross a
 * line you care about, such as `is_scammer >= 90`.
 */
export class RulesResource {
  constructor(private readonly core: Core) {}

  /**
   * List rules.
   *
   * `GET /v1/rules`
   */
  list(options?: RequestOptions): Promise<T.RuleList> {
    return this.core.request<T.RuleList>(
      {
        method: "GET",
        path: "/v1/rules",
      },
      options,
    );
  }

  /**
   * Create a rule.
   *
   * The condition is validated against the tenant's signals, and a `webhook` action must
   * reference a registered endpoint subscribed to `rule.triggered`.
   *
   * `POST /v1/rules`
   */
  create(body: T.RuleCreate, options?: RequestOptions): Promise<T.Rule> {
    return this.core.request<T.Rule>(
      {
        method: "POST",
        path: "/v1/rules",
        body,
      },
      options,
    );
  }

  /**
   * Get a rule.
   *
   * `GET /v1/rules/{rule_id}`
   */
  get(ruleId: string, options?: RequestOptions): Promise<T.Rule> {
    return this.core.request<T.Rule>(
      {
        method: "GET",
        path: "/v1/rules/{rule_id}",
        pathParams: { rule_id: ruleId },
      },
      options,
    );
  }

  /**
   * Update a rule.
   *
   * Omitted fields are left unchanged. The resulting condition and action are re-validated.
   *
   * `PATCH /v1/rules/{rule_id}`
   */
  update(ruleId: string, body: T.RuleUpdate, options?: RequestOptions): Promise<T.Rule> {
    return this.core.request<T.Rule>(
      {
        method: "PATCH",
        path: "/v1/rules/{rule_id}",
        pathParams: { rule_id: ruleId },
        body,
      },
      options,
    );
  }

  /**
   * Delete a rule.
   *
   * `DELETE /v1/rules/{rule_id}`
   */
  delete(ruleId: string, options?: RequestOptions): Promise<void> {
    return this.core.request<void>(
      {
        method: "DELETE",
        path: "/v1/rules/{rule_id}",
        pathParams: { rule_id: ruleId },
      },
      options,
    );
  }
}

/**
 * A rule fires an action (email, Slack or webhook) when an object's signal values cross a
 * line you care about, such as `is_scammer >= 90`.
 */
export class RuleFiringsResource {
  constructor(private readonly core: Core) {}

  /**
   * List rule firings.
   *
   * The audit log of rule firings and their action outcomes, newest first.
   *
   * `GET /v1/rule_firings`
   */
  list(params?: ListRuleFiringsParams, options?: RequestOptions): Promise<T.RuleFiringList> {
    return this.core.request<T.RuleFiringList>(
      {
        method: "GET",
        path: "/v1/rule_firings",
        query: params,
      },
      options,
    );
  }
}

/** Create, rotate and revoke the keys your integrations sign requests with. */
export class ApiKeysResource {
  constructor(private readonly core: Core) {}

  /**
   * List API keys.
   *
   * Revoked keys are not listed. Secrets are never returned.
   *
   * `GET /v1/api_keys`
   */
  list(options?: RequestOptions): Promise<T.ApiKeyList> {
    return this.core.request<T.ApiKeyList>(
      {
        method: "GET",
        path: "/v1/api_keys",
      },
      options,
    );
  }

  /**
   * Create an API key.
   *
   * Mints a key ID and signing secret. **The secret is shown only once.**
   *
   * `POST /v1/api_keys`
   */
  create(body: T.ApiKeyCreate, options?: RequestOptions): Promise<T.ApiKeySecret> {
    return this.core.request<T.ApiKeySecret>(
      {
        method: "POST",
        path: "/v1/api_keys",
        body,
      },
      options,
    );
  }

  /**
   * Update an API key.
   *
   * Rename a key, or deactivate and reactivate it. Use `DELETE` to revoke.
   *
   * `PATCH /v1/api_keys/{key_id}`
   */
  update(keyId: string, body: T.ApiKeyUpdate, options?: RequestOptions): Promise<T.ApiKey> {
    return this.core.request<T.ApiKey>(
      {
        method: "PATCH",
        path: "/v1/api_keys/{key_id}",
        pathParams: { key_id: keyId },
        body,
      },
      options,
    );
  }

  /**
   * Revoke an API key.
   *
   * The key stops authenticating immediately. Its ID is never reissued.
   *
   * `DELETE /v1/api_keys/{key_id}`
   */
  revoke(keyId: string, options?: RequestOptions): Promise<void> {
    return this.core.request<void>(
      {
        method: "DELETE",
        path: "/v1/api_keys/{key_id}",
        pathParams: { key_id: keyId },
      },
      options,
    );
  }

  /**
   * Rotate an API key's secret.
   *
   * Keeps the key ID and replaces the secret. The old secret stops working immediately; the
   * new one is returned only once.
   *
   * `POST /v1/api_keys/{key_id}/rotate`
   */
  rotate(keyId: string, options?: RequestOptions): Promise<T.ApiKeySecret> {
    return this.core.request<T.ApiKeySecret>(
      {
        method: "POST",
        path: "/v1/api_keys/{key_id}/rotate",
        pathParams: { key_id: keyId },
      },
      options,
    );
  }
}

/** Prepaid balance, the billing ledger, and card top-ups. */
export class BillingResource {
  constructor(private readonly core: Core) {}

  /**
   * Get the prepaid balance.
   *
   * `GET /v1/billing`
   */
  getBalance(options?: RequestOptions): Promise<T.Balance> {
    return this.core.request<T.Balance>(
      {
        method: "GET",
        path: "/v1/billing",
      },
      options,
    );
  }

  /**
   * List ledger entries.
   *
   * One page of the billing ledger, newest first. Pass the previous page's `next_cursor` as
   * `cursor` to continue; it is empty on the last page.
   *
   * `GET /v1/billing/ledger`
   */
  listLedger(params?: ListLedgerParams, options?: RequestOptions): Promise<T.LedgerPage> {
    return this.core.request<T.LedgerPage>(
      {
        method: "GET",
        path: "/v1/billing/ledger",
        query: params,
      },
      options,
    );
  }

  /**
   * Start a card top-up.
   *
   * Creates a hosted Stripe Checkout Session for the amount and returns its URL. The balance
   * is credited only once Stripe confirms the payment. Returns `503` when card payments are
   * not configured.
   *
   * `POST /v1/billing/checkout`
   */
  createCheckout(body: T.CheckoutCreate, options?: RequestOptions): Promise<T.CheckoutSession> {
    return this.core.request<T.CheckoutSession>(
      {
        method: "POST",
        path: "/v1/billing/checkout",
        body,
      },
      options,
    );
  }

  /**
   * Get a top-up's status.
   *
   * Whether the Checkout Session's payment has been credited to the balance yet.
   *
   * `GET /v1/billing/checkout/{session_id}`
   */
  getCheckout(sessionId: string, options?: RequestOptions): Promise<T.CheckoutStatus> {
    return this.core.request<T.CheckoutStatus>(
      {
        method: "GET",
        path: "/v1/billing/checkout/{session_id}",
        pathParams: { session_id: sessionId },
      },
      options,
    );
  }
}

/** Analysis volume, spend and token usage over a date range. */
export class UsageResource {
  constructor(private readonly core: Core) {}

  /**
   * Get usage.
   *
   * Analyses, spend and tokens over an inclusive UTC date range (at most 366 days), with a
   * zero-filled daily series and breakdowns by model, source (`async` / `sync`) and signal.
   * Defaults to the last 30 days.
   *
   * `GET /v1/usage`
   */
  get(params?: GetUsageParams, options?: RequestOptions): Promise<T.Usage> {
    return this.core.request<T.Usage>(
      {
        method: "GET",
        path: "/v1/usage",
        query: params,
      },
      options,
    );
  }
}
