// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

import { createHmac, timingSafeEqual } from "node:crypto";
import type { WebhookEvent } from "./models.js";

/** The signature, timestamp or payload of a webhook delivery is not valid. */
export class WebhookVerificationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "WebhookVerificationError";
  }
}

export interface VerifyOptions {
  /** Reject deliveries signed longer ago than this, in seconds. Default 300. */
  tolerance?: number;
  /** The current time in Unix seconds, for tests. */
  now?: number;
}

/**
 * Verifies a webhook delivery: `X-Webhook-Signature` must be the HMAC-SHA256
 * of `"<X-Webhook-Timestamp>.<raw body>"` keyed with the endpoint secret, and
 * the timestamp must be recent. Pass the raw body, exactly as received.
 */
export function verifyWebhookSignature(
  payload: string | Uint8Array,
  signature: string | null | undefined,
  timestamp: string | null | undefined,
  secret: string,
  options: VerifyOptions = {},
): void {
  if (!signature || !timestamp) throw new WebhookVerificationError("missing signature or timestamp header");
  const ts = Number(timestamp);
  if (!Number.isInteger(ts)) throw new WebhookVerificationError("invalid timestamp");
  const now = options.now ?? Math.floor(Date.now() / 1000);
  const tolerance = options.tolerance ?? 300;
  if (tolerance > 0 && Math.abs(now - ts) > tolerance) throw new WebhookVerificationError("timestamp outside the tolerance");

  const mac = createHmac("sha256", secret);
  mac.update(`${timestamp}.`);
  mac.update(payload);
  const expected = Buffer.from("sha256=" + mac.digest("hex"));
  const given = Buffer.from(signature);
  if (expected.length !== given.length || !timingSafeEqual(expected, given)) {
    throw new WebhookVerificationError("signature mismatch");
  }
}

/** Verifies a webhook delivery (see verifyWebhookSignature) and parses its body. */
export function constructWebhookEvent(
  payload: string | Uint8Array,
  signature: string | null | undefined,
  timestamp: string | null | undefined,
  secret: string,
  options: VerifyOptions = {},
): WebhookEvent {
  verifyWebhookSignature(payload, signature, timestamp, secret, options);
  const text = typeof payload === "string" ? payload : Buffer.from(payload).toString("utf8");
  try {
    return JSON.parse(text) as WebhookEvent;
  } catch {
    throw new WebhookVerificationError("payload is not valid JSON");
  }
}
